const projectsData = [
    {
        id: 1,
        clientName: "Reduxpay",
        description: "Reduxpay is a trusted Gold Standard in the Payment Solutions category. Now an app-based platform empowering businesses to integrate and manage payments seamlessly. Accept payments via multiple methods like UPI, wallets, and more, all with the convenience of a secure, user-friendly interface.",
        services: 'UI/UX • Payment Gateway • Backend',
        img: '/Group37.svg',
        goals: ['Support Multiple Payment Methods', 'Provide an Easy Integration API for Businesses', 'User Dashboard for Real-time Transaction Tracking', 'Fast, Secure, and Reliable Payment Processing'],
        technologies: ["React", "Node.js", "MongoDB", "Stripe"],
        images: [
            "/reduxscreen2.png",
            "/screen3.png",
            "/reduxscreen1.png",
            "/reduxscreen4.png",
            "/reduxscreen5.png",
        ],
    },
    {
        id: 2,
        clientName: "Venue Original",
        description: "Venue Original is a trusted Gold Standard in the Fashion and Lifestyle category. Now an app-based shopping platform, making it easy to browse and shop the latest fashion trends, from clothing to accessories, all with the convenience of a seamless, personalized experience right at your fingertips.",
        services: 'UI/UX • Shopify • E-Commerce',
        img: '/project2.svg',
        goals: [
            'Browse Products by Category and Price Range',
            'Design a Custom Wishlist or Personalized Shopping',
            'User Registers for Account Management and Order Tracking',
            'Simple, Fast, and Secure Checkout Process',
        ],
        technologies: ["React", "Node.js", "MongoDB", "Stripe"],
        images: [
            "/venue1.png",
            "/venue2.png",
            "/venue3.png",
            "/venue4.png",
            "/venue5.png",
        ],
    },
    // {
    //     id: 3,
    //     clientName: "Skill Go",
    //     description: "SkillGo serves as a trusted gateway to excellence in education and skill development. Recognized as a leader in online learning, they empower students worldwide to master new skills, elevate their careers, and thrive in the digital era. With intuitive courses, expert guidance, and industry-recognized certifications, SkillGo helps individuals reach their full potential.",
    //     services: 'UI/UX • Landing Page • Frontend',
    //     img: '/skillgo.svg',
    //     goals: [
    //         'Provide Accessible and Engaging Online Learning',
    //         'Empower Learners with Expert-Led Courses',
    //         'Facilitate Skill Development with Certification Programs',
    //         'Build a Collaborative Community for Growth',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //         "/skillgo1.png",
    //         "/skillgo2.png",
    //         "/skillgo3.png",
    //         "/skillgo4.png",
    //         "/skillgo5.png",
    //     ],
    // },
    {
        id: 4,
        clientName: "Top Fit",
        description: "TopFit is a premier destination for fitness enthusiasts and professionals, offering personalized training programs alongside high-quality gym apparel and accessories. Designed to elevate your fitness journey, their platform seamlessly combines expert-led classes, fitness tools, and a curated shop for athletic wear. With cutting-edge features, secure purchasing options, and a sleek user experience, TopFit is your ultimate partner for achieving health and style goals.",
        services: 'Frontend • UI • Payment Gateway',
        img: '/topfitmain.svg',
        goals: [
            'Offer Personalized Fitness Training Programs',
        'Provide High-Quality Gym Wear and Accessories',
        'Create a Community for Fitness Enthusiasts',
        'Deliver Secure and Easy Online Shopping Experience',
        ],
        technologies: ["React", "Node.js", "MongoDB", "Stripe"],
        images: [
        "/topfit1.png",
       "/topfit2.png",
       "/topfit3.png",
       "/topfit4.png",
       "/topfit5.png",
        ],
    },
    // {
    //     id: 5,
    //     clientName: "Piquant",
    //     description: "Piquant is a trusted name in the culinary world, known for offering delectable recipes, expertly crafted menus, and a premium dining experience. With their user-friendly platform, food enthusiasts can explore unique dishes, make reservations, and shop for top-rated products with ease. Enjoy a seamless journey through flavors, all while savoring the convenience of a secure, well-designed interface.",
    //     services: 'UI/UX • Database • Backend',
    //     img: '/piquant.svg',
    //     goals: [
    //         'Offer a Wide Range of Gourmet Recipes for All Tastes',
    //     'Provide an Easy-to-Use Reservation System for Diners',
    //     'Create a Seamless Shopping Experience for Food Products',
    //     'Deliver High-Quality Ingredients and Cooking Tips',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //        "/Piquant1.png",
    //     "/Piquant2.png",
    //     "/Piquant3.png",
    //     "/Piquant4.png",
    //     "/Piquant5.png",
    //     ],
    // },
    // {
    //     id: 6,
    //     clientName: "Petty",
    //     description: "Petty is a dedicated pet care brand specializing in providing high-quality pet food, accessories, and grooming products. Alongside their extensive product range, Petty offers valuable resources for pet owners, including expert tips on pet care and information on pet adoption, creating a one-stop destination for all pet-related needs.",
    //     services: 'UI/UX • Landing Page • Frontend',
    //     img: '/Projects/petty/petty.svg',
    //     goals: [
    //         'Build a seamless e-commerce platform for pet products',
    //         'Offer an interactive adoption section with pet profiles',
    //         'Provide personalized recommendations for pet care.',
    //         'Ensure a dynamic, mobile-friendly interface for all users',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //         "/Projects/petty/petty1.png",
    //         "/Projects/petty/petty2.png",
    //         "/Projects/petty/petty3.png",
    //         "/Projects/petty/petty4.png",
    //         "/Projects/petty/petty5.png",
    //     ],
    // },
    // {
    //     id: 7,
    //     clientName: "Fodis",
    //     description: "Fodis is a vibrant food delivery platform that connects users with a wide range of local restaurants and eateries, delivering freshly prepared meals right to their doorsteps. With an easy-to-navigate interface, Fodis ensures a seamless and efficient ordering experience. Whether it’s a quick snack or a gourmet meal, Fodis is committed to satisfying every craving while maintaining quality and promptness, making it a trusted partner for food lovers everywhere.",
    //     services: 'UI/UX • Landing Page • Frontend',
    //     img: '/Projects/fodies/fodis.svg',
    //     goals: [
    //         'Create a visually engaging and intuitive user interface.',
    //         'Ensure reliable and fast delivery system integration',
    //         'Enable real-time order tracking and updates for users.',
    //         'Develop a mobile-responsive and user-friendly interface'
            
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //         "/Projects/fodies/fodies1.png",
    //         "/Projects/fodies/fodies2.png",
    //         "/Projects/fodies/fodies3.png",
    //         "/Projects/fodies/fodies4.png",
    //         "/Projects/fodies/fodies5.png",
    //     ],
    // },
    // {
    //     id: 8,
    //     clientName: "The Elegant",
    //     description: "Elegant is a unique jewelry brand specializing in the online sale of beautifully crafted artificial jewelry. Their in-house designs blend contemporary trends with timeless elegance, offering a wide range of options for every occasion. From statement pieces to delicate accessories, Elegant caters to modern fashion enthusiasts seeking affordability without compromising on style or quality..",
    //     services: 'UI/UX • Landing Page • Frontend',
    //     img: '/Projects/elegant/elegant.svg',
    //     goals: [
    //         'Showcase the complete range of in-house jewelry designs.',
    //         'Enable secure and easy online transactions.',
    //         'Optimize the platform for mobile and tablet devices.',
    //         'Provide high-quality visuals to highlight product details.',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //         "/Projects/elegant/elegant1.png",
    //         "/Projects/elegant/elegant2.png",
    //         "/Projects/elegant/elegant3.png",
    //         "/Projects/elegant/elegant4.png",
    //         "/Projects/elegant/elegant5.png",
    //     ],
    // },
    // {
    //     id: 9,
    //     clientName: "Echooling",
    //     description: "Echooling is an innovative and inclusive educational platform dedicated to creating a transformative learning experience for students worldwide. With an emphasis on academic excellence and personal development, Echooling bridges the gap between traditional and modern education through cutting-edge technology, interactive courses, and a supportive community. It empowers learners to achieve their goals while fostering a love for knowledge and exploration.",
    //     services: 'UI/UX • Blogs • Backend',
    //     img: '/Projects/Echooling/eschooling.svg',
    //     goals: [
    //         'Creating a Comprehensive Educational Ecosystem to Nurture Student Growth',
    //     'Promoting the Integration of Modern Technology in Academic Programs',
    //     'Building a Collaborative and Inclusive Learning Community for Students',
    //     'Offering Opportunities for Professional Development and Lifelong Education',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //        "/Projects/Echooling/Echolling2.png",
    //     "/Projects/Echooling/Echolling3.png",
    //     "/Projects/Echooling/Echolling4.png",
    //     "/Projects/Echooling/Echolling5.png",
    //     "/Projects/Echooling/Echolling6.png",
    //     ],
    // },
    // {
    //     id: 10,
    //     clientName: "Grabit",
    //     description: "GrabIt is an online marketplace offering a wide range of everyday essentials, including fresh fruits, vegetables, bakery items, dairy products, snacks, spices, and more. With a focus on quality and affordability, Grab It ensures a seamless shopping experience for customers looking to stock their pantry with organic and high-quality food products.",
    //     services: 'UI/UX • Landing Page • Frontend',
    //     img: '/Projects/grabit/grabit.svg',
    //     goals: [
    //         'Promote a health-centric shopping experience for customers.g',
    //         'Support multiple categories, including fresh produce and snacks.',
    //         'Provide discount and deal integration for real-time offers.',
    //         'Create a dynamic user dashboard to track orders and rewards.',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //         "/Projects/grabit/grabit1.png",
    //         "/Projects/grabit/grabit2.png",
    //         "/Projects/grabit/grabit3.png",
    //         "/Projects/grabit/grabit4.png",
    //         "/Projects/grabit/grabit5.png",
    //     ],
    // },
    // {
    //     id: 11,
    //     clientName: "Gymate",
    //     description: "Gymate is a leading fitness brand offering personalized training programs tailored to individual goals and lifestyles. Alongside expert coaching, Gymate specializes in the sale of high-quality gym and fitness equipment, making it a one-stop destination for all fitness enthusiasts striving to achieve their health and wellness aspirations.",
    //     services: 'UI/UX • Landing Page • Frontend',
    //     img: '/Projects/gymate/gymate.svg',
    //     goals: [
    //         'Offer personalized training plans with online booking options',
    //         'Build a seamless e-commerce store for fitness equipment',
    //         'Ensure a dynamic, mobile-friendly interface for all users',
    //         'Build a seamless e-commerce store for fitness equipment',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //         "/Projects/gymate/gymate1.png",
    //         "/Projects/gymate/gymate2.png",
    //         "/Projects/gymate/gymate3.png",
    //         "/Projects/gymate/gymate4.png",
    //         "/Projects/gymate/gymate5.png",
    //     ],
    // },
    // {
    //     id: 12,
    //     clientName: "Hendon",
    //     description: "Hendon is a premium real estate platform specializing in luxurious apartments and exclusive property options in prime locations. With a focus on sophistication and expertise, Hendon curates exceptional living spaces that redefine modern luxury, catering to clients seeking the perfect blend of comfort, elegance, and convenience.",
    //     services: 'UI/UX • Landing Page • Booking Service',
    //     img: '/Projects/hendon/hendon.svg',
    //     goals: [
    //         'Highlight premium apartments and properties with detailed specifications',
    //         'Provide virtual tours and high-quality images for propertiess',
    //         'Enable secure communication between buyers and property consultants',
    //         'Reflect the brand’s luxury focus through a modern, elegant design',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //         "/Projects/hendon/hendon1.png",
    //         "/Projects/hendon/hendon2.png",
    //         "/Projects/hendon/hendon3.png",
    //         "/Projects/hendon/hendon4.png",
    //         "/Projects/hendon/hendon5.png",
    //     ],
    // },
    // {
    //     id: 13,
    //     clientName: "Mavis",
    //     description: "Mavis is a trusted name in the field of cosmetic and reconstructive surgery, offering personalized treatments that combine advanced techniques with exceptional care. With a team of highly skilled specialists and over 25 years of experience, Mavis focuses on empowering clients to achieve their aesthetic and personal goals. From precision-driven cosmetic surgeries to premium skincare and nutrition products.",
    //     services: 'UI/UX • Landing Page • Frontend',
    //     img: '/Projects/mavis/mavis.svg',
    //     goals: [
    //         'Showcase cosmetic surgery services with detailed information',
    //         'Create a booking system for consultations and treatments',
    //         'Include a gallery and testimonials for client confidence',
    //         'Ensure a clean and professional user interface reflecting the brand`s expertise',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //         "/Projects/mavis/mavis1.png",
    //         "/Projects/mavis/mavis2.png",
    //         "/Projects/mavis/mavis3.png",
    //         "/Projects/mavis/mavis4.png",
    //         "/Projects/mavis/mavis5.png",
    //     ],
    // },
    // {
    //     id: 14,
    //     clientName: "Iva",
    //     description: "Iva is a skincare brand in the cosmetics category, specializing in high-quality products for skincare and personal care. With a focus on enhancing natural beauty, Iva offers a wide range of solutions tailored to nourish, protect, and rejuvenate the skin, catering to diverse skincare needs.",
    //     services: 'UI/UX • Landing Page • Frontend',
    //     img: '/Projects/iva/iva.svg',
    //     goals: [
    //         'Develop a comprehensive catalog for skincare and personal care products',
    //         'Include a blog for skincare tips and product usage guides',
    //         'Optimize for fast loading and smooth navigation on all devices',
    //         'Provide an easy-to-use interface with advanced search filters',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //         "/Projects/iva/iva1.png",
    //         "/Projects/iva/iva2.png",
    //         "/Projects/iva/iva3.png",
    //         "/Projects/iva/iva4.png",
    //         "/Projects/iva/iva5.png",
    //     ],
    // },
    
    // {
    //     id: 15,
    //     clientName: "Paheli",
    //     description: "Paheli Cyber is a comprehensive cybersecurity platform dedicated to protecting organizations from evolving cyber threats. With a focus on innovation and expertise, Paheli Cyber empowers businesses with advanced security solutions, from application to infrastructure security, and beyond. By leveraging cutting-edge technology, intuitive tools, and a team of skilled professionals, Paheli Cyber ensures the seamless safeguarding of systems, data, and networks",
    //     services: 'Frontend • Database • Blogs',
    //     img: '/Projects/Paheli/paheli.svg',
    //     goals: [
    //         'Deliver Comprehensive Cybersecurity Solutions Across All Sectors',
    //     'Provide Cutting-Edge Tools for Advanced Threat Detection',
    //     'Enable Organizations to Build Strong Cybersecurity Policies',
    //     'Facilitate Seamless Integration of Security Infrastructure',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //        "/Projects/Paheli/Paheli2.png",
    //     "/Projects/Paheli/Paheli3.png",
    //     "/Projects/Paheli/Paheli4.png",
    //     "/Projects/Paheli/Paheli5.png",
    //     "/Projects/Paheli/Paheli6.png",
    //     ],
    // },
    // {
    //     id: 16,
    //     clientName: "Ailife",
    //     description: "AIlife is an innovative AI-driven content generation platform designed to simplify and accelerate the creation of high-quality written material. With a focus on speed and precision, AI Life empowers businesses, individuals, and content creators by offering advanced tools for generating blog posts, ad copies, website content, and more. The platform incorporates cutting-edge language AI, ensuring diverse use cases, creative solutions, and multilingual support, all within a user-friendly interface.",
    //     services: 'AI • SEO • UI/UX',
    //     img: '/Projects/Ailife/ailife.svg',
    //     goals: [
    //         'Empower Users with Lightning-Fast Content Generation Tools',
    //     'Provide Comprehensive Solutions Across 30+ Content Use Cases',
    //     'Expand Global Reach Through Advanced Multilingual Capabilities',
    //     'Ensure Consistently High-Quality, SEO-Friendly, and Original Outputs',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //        "/Projects/Ailife/Ailife2.png",
    //     "/Projects/Ailife/Ailife3.png",
    //     "/Projects/Ailife/Ailife4.png",
    //     "/Projects/Ailife/Ailife5.png",
    //     "/Projects/Ailife/Ailife6.png",
    //     ],
    // },
    // {
    //     id: 17,
    //     clientName: "Canyon",
    //     description: "Canyon is a beacon of transformative education, dedicated to fostering intellectual growth, creativity, and innovation. It offers a comprehensive range of undergraduate and graduate programs tailored to meet the needs of a diverse student body. With a strong emphasis on experiential learning, inclusive campus life, and academic excellence, Canyon empowers students to reach their highest potential.",
    //     services: 'Frontend • Maps • UI/UX',
    //     img: '/Projects/Canyon/canyon.svg',
    //     goals: [
    //         'Deliver Transformative and Inclusive Education Across Disciplines',
    //     'Foster Experiential Learning and Real-World Engagement',
    //     'Expand Access to Cutting-Edge Resources and Faculty Expertise',
    //     'Empower Students with Advanced Career-Ready Skills',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //        "/Projects/Canyon/Canyon5.png",
    //     "/Projects/Canyon/Canyon7.png",
    //     "/Projects/Canyon/Canyon8.png",
    //     "/Projects/Canyon/Canyon9.png",
    //     "/Projects/Canyon/Canyon3.png",
    //     ],
    // },
    // {
    //     id: 18,
    //     clientName: "Furious",
    //     description: "Furious is a premier brand specializing in the sale and rental of luxury cars, offering an unmatched selection of high-end vehicles. Designed for clients who value sophistication and comfort, Furious combines a passion for automobiles with exceptional customer service. Whether it’s for a special occasion or a high-profile business trip, Furious provides a seamless experience, ensuring that every drive is as luxurious as the car itself.",
    //     services: 'UI/UX • Landing Page • Frontend',
    //     img: '/Projects/furious/furious.svg',
    //     goals: [
    //         'Create a searchable inventory of luxury cars for sale and rent.',
    //         'Develop a booking system with real-time availability.',
    //         'Design a premium and elegant user interface to reflect the brand.',
    //         'Optimize the platform for mobile and tablet devices.',
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //         "/Projects/furious/furious1.png",
    //         "/Projects/furious/furious2.png",
    //         "/Projects/furious/furious3.png",
    //         "/Projects/furious/furious4.png",
    //         "/Projects/furious/furious5.png",
    //     ],
    // },
    // {
    //     id: 19,
    //     clientName: "Shapen",
    //     description: "Shapen specializes in delivering state-of-the-art construction projects tailored to meet unique client requirements. From robust concrete structures to intricate interior designs, Shapen ensures durability, functionality, and aesthetic appeal in every project.",
    //     services: 'UI/UX • Blogs • Backend',
    //     img: '/Projects/Shapen/shapne.svg',
    //     goals: [
    //     "Innovative structural designs for modern architecture",
    //     "Sustainable and durable construction practices",
    //     "High-quality materials for premium results",
    //     "Tailored solutions for diverse project needs"
    //     ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //        "/Projects/Shapen/Shapen2.png",
    //     "/Projects/Shapen/Shapen3.png",
    //     "/Projects/Shapen/Shapen4.png",
    //     "/Projects/Shapen/Shapen7.png",
    //     "/Projects/Shapen/Shapen5.png",
    //     ],
    // },
    // {
    //     id: 20,
    //     clientName: "Zivan",
    //     description: "Zivan is a leading creative digital marketing and design agency dedicated to crafting unique brand identities and impactful campaigns. By combining innovative strategies, cutting-edge technology, and a passionate team of experts, Zivan delivers customized solutions that enhance businesses' online presence, strengthen their brand value, and drive measurable results.",
    //     services: 'UI/UX • Frontend • DataBase',
    //     img: '/Projects/Zivan/zivan.svg',
    //     goals: [
    //     "Establishing unique and effective brand strategies",
    //     "Promoting innovative and result-driven marketing solutions",
    //     "Fostering creative design to enhance digital presence",
    //     "Integrating advanced AI systems for better insights"
    // ],
    //     technologies: ["React", "Node.js", "MongoDB", "Stripe"],
    //     images: [
    //        "/Projects/Zivan/Zivan1.png",
    //     "/Projects/Zivan/Zivan3.png",
    //     "/Projects/Zivan/Zivan2.png",
    //     "/Projects/Zivan/Zivan4.png",
    //     "/Projects/Zivan/Zivan6.png",
    //     ],
    // },

   
];

export default projectsData;